#!/bin/sh
ssh cc2-user@13.125.206.128:3000 <<EOF
    cd ~/jenkins-tutorial
    git pull origin master
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install 15.9.0
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF